blank_issues_enabled: false
contact_links:
  - name: Conduit Issue Tracker ğŸ–¥ï¸
    url: https://github.com/ConduitPlatform/Conduit/issues
    about: Report issues related to Conduit (backend)
  - name: Admin Panel Issue Tracker ğŸ’»
    url: https://github.com/ConduitPlatform/Conduit-UI/issues
    about: Report issues related to Conduit Admin Panel
  - name: Documentation ğŸ“„
    url: https://getconduit.dev/docs/overview/intro
    about: Check out our Documentation
  - name: Need Assistance? ğŸ†˜
    url: https://discord.gg/hWnW2aJDrE
    about: Reach us on Discord
